name: macOS Build
on: workflow_dispatch

jobs:
  build_with_signing:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Make Dotenv
        run: echo "$DOTENV" > .env
        env:
          DOTENV: ${{ secrets.DOTENV }}

      - name: Make App
        run: yarn package

      # - name: Sign App
      #   run: yarn electron-osx-sign --deep "./out/왁타버스 뮤직-darwin-x64/왁타버스 뮤직.app"

      # - name: Sign App
      #   run: codesign --force --verify -v -vvvv --timestamp --sign 4C9ACD1C8A0C955DA214277A9308ACD6DA59A471 "./out/왁타버스 뮤직-darwin-x64/왁타버스 뮤직.app"

      - name: Sign binary
        uses: lando/code-sign-action@v2
        with:
          file: out/왁타버스 뮤직-darwin-x64/왁타버스 뮤직.app
          certificate-data: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          apple-notary-user: ${{ secrets.APPLE_NOTARY_USER }}
          apple-notary-password: ${{ secrets.APPLE_NOTARY_PASSWORD }}
          apple-notary-tool: altool
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          apple-product-id: com.wakmusic-pc
          options: --options runtime --entitlements ./build/macos/entitlements.plist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 왁타버스 뮤직
          path: "./out"
