name: macOS Build
on: workflow_dispatch

jobs:
  build_with_signing:
    runs-on: [macOS, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Make Dotenv
        run: echo "$DOTENV" > .env
        env:
          DOTENV: ${{ secrets.DOTENV }}

      - name: Make App
        run: yarn make
        env:
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 왁타버스 뮤직 macOS DMG
          path: "./out/make"
